### ISSUE TITLE
can't run data loader

### ISSUE THREAD

**Issue by markjbrown** [mspnp/azure-stream-analytics-data-pipeline#1]
I tried running this sample but had issues running the data load in a docker container. Was running on Docker for Windows. First issue was the relative paths to where the data and csproj were located was not correct in the instructions. However, after fixing that, docker complained about not being able to mount the volume where the data was loaded.

**Comment by v-fearam** [comment]
Sorry @markjbrown for the delay.
The paths were not correct. Thanks for let us notice. 

Related to docker for windows, please take into account share the drive which is required to mount volumes.
I was able to do the deploy using docker for windows today.

https://docs.docker.com/docker-for-windows/#file-sharing
https://docs.docker.com/docker-for-windows/troubleshoot/#volume-mounting-requires-shared-drives-for-linux-containers
![image](https://user-images.githubusercontent.com/62260324/82952168-dcf59880-9f7e-11ea-9b40-17d1286422ba.png)

I will close, but let free to re open or create a new one if it is needed.
