### ISSUE TITLE
Stream Analytics Query is not working as expected

### ISSUE THREAD

**Issue by swatiBabber** [mspnp/azure-stream-analytics-data-pipeline#5]
Tried running this solution , The Pickup Datetime condition in join Step 3 is not returning any results.
Looks like format of dates is different in Step 1 and Step 2.
Can you please help?

**Comment by magrande** [comment]
@swatiBabber Thanks for raising this issue. We found the problem in the query file, the column name being used in Step1 is not right. A solution to this issue is going to be live soon. We are closing this for now. Thank you.
